#!/usr/bin/env bash

SERVICE_FILE="macvlan0.service"
SERVICE_PATH="/etc/systemd/system/$SERVICE_FILE"

echo "Setting up macvlan service"
if [ ! -L "$SERVICE_PATH" ]; then
    ln -s "$(pwd)/$SERVICE_FILE" "$SERVICE_PATH"
fi
systemctl enable "$SERVICE_FILE"
systemctl restart "$SERVICE_FILE"

# ---

MACVLAN_NET="macvlan"

echo "Setting up macvlan docker network"
if ! docker network ls --format '{{.Name}}' | grep -q "^$MACVLAN_NET\$"; then
    docker network create -d macvlan \
        --subnet=192.168.50.0/24 \
        --ip-range=192.168.50.248/29 \
        --gateway=192.168.50.1 \
        -o parent=eth0 \
        "$MACVLAN_NET"
fi

# ---

TRAEFIK_NET="traefik"

echo "Setting up traefik docker network"
if ! docker network ls --format '{{.Name}}' | grep -q "^$TRAEFIK_NET\$"; then
    docker network create "$TRAEFIK_NET"
fi
